version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    strategy:
      versioning-strategy: 'lockfile-only'
    reviewers:
      - 'ryo-manba'
